### ISSUE TITLE
Roadmap to first release

### ISSUE THREAD

**Issue by MarcoRuzzon** [ADVRHumanoids/forest#11]
- [x] binary dependencies (system vs local) : 
use recipes to install binaries (type: deb) recipes names are still cmake-packages names (name of bin specified inside the recipe, env should be accessible for variable expansion, at least.)
- [x] full list of recipes for fresh install of xbot2 on non real time machines
   TESTED using docker container (from within forest folder run ./docker-run.sh -p forest -d bionic -j8): succesful build and dummy run

- forest: commit 51d4f006bf543ba10209405a9437e727bc5fec80 (HEAD -> mr_devel, origin/mr_devel)
    Date:   Fri Jul 30 15:28:05 2021 +0200
    (docker): update script to be run inside docker container

- forest-recipes: commit a974a9633888d737bcb9290f9138536c1f0b8d7a (HEAD -> xeno, origin/xeno)
   Date:   Fri Jul 30 14:59:13 2021 +0200
   add zmq dep to cppzmq

- [x] full list of recipes for fresh install of xbot2 on real-time machine (tree-pc1 with xenomai):
We have a list of recipes to build xbot2 on a real-time machine using the args --mode xeno: 
- forest-recipes: commit 36971a2a737a3dc1ff12a183a55e048e4e7b97e8

To test them properly we compile xbot2 (`forest all --mode xeno`), run `xbot2-core --hw dummy` inside a docker container and we check that *rt_main* is truly real-time (see [Zube #1015](https://zube.io/tree-2/tree/c/1015)), see detailed card [Zube #1020](https://zube.io/tree-2/tree/c/1020)
