### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/forest#36]
Todo list
 - [x] support for ros source trees #32
 - [x] recipe as source #31 
 - [x] simpler password management #35 
 - [ ] documentation #37
 - [x] unit testing, CI, CD #38
